name = "glecuid"
version = "1.0.5"

licences = ["MIT"]
description = "A Gleam implementation of CUID2, the secure, collision-resistant ids optimized for horizontal scaling and performance."

repository = { type = "github", user = "ilhamft", repo = "glecuid" }
links = [
  { title = "Package", href = "https://hex.pm/packages/glecuid" },
  { title = "Docs", href = "https://hexdocs.pm/glecuid" },
]

internal_modules = ["glecuid/internals/*"]

[dependencies]
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
bigi = ">= 4.1.0 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleeunit = ">= 1.6.1 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
