name: release

on:
  push:
    tags: ['v*']

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '28'
          rebar3-version: '3'
          gleam-version: '1.13.0'
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: check version
        run: |
          version="v$(cat gleam.toml | grep -m 1 "version" | sed -r "s/version *= *\"([[:digit:].]+)\"/\1/")"
          if [ "$version" != "${{ github.ref_name }}" ]; then
            echo "tag '${{ github.ref_name }}' does not match the version in gleam.toml"
            echo "expected a tag name '$version'"
            exit 1
          fi

      - run: gleam deps download
      - run: gleam format --check

      - run: gleam publish -y
        env:
          HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}

      - uses: softprops/action-gh-release@v2
